version: '3.7'
services:

  backend:
    image: "gcr.io/qualitool/qualitool_be"
    container_name: qualitool_be
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8082:8082

      
  frontend:
    image: "gcr.io/qualitool/qualitool_fe"
    container_name: qualitool_fe
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443

      
