version: '3.7'
services:
  database:
    image: "postgres"
    container_name: qualitool_db
    ports:
      - 5432:5432
    env_file:
      - qualitool.env
    volumes:
      - database-data:/var/lib/postgresql/data
#      - type: bind
#        source: ./persist/pgdata/
#        target: /var/lib/postgresql/data
  backend:
    image: "gcr.io/qualitool/qualitool_be"
    container_name: qualitool_be
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    env_file:
      - qualitool.env
    volumes:
     - ./cert:/cert
     - ./static:/static
     - ./init:/init
      
  frontend:
    image: "gcr.io/qualitool/qualitool_fe"
    container_name: qualitool_fe
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    #volumes:
    #  - '.:/app'
    #  - '/app/node_modules'
    ports:
      - 80:80
      - 443:443
    volumes:
      #- ./frontend/certs:/etc/nginx/certs
      - ./cert:/etc/nginx/certs
    #environment:
    #  - NODE_ENV=development
        
volumes:
  database-data:
#    driver: local
#    driver_opts:
#      source: persist/pgdata/