version: '3.7'
services:
  database:
    image: "postgres"
    container_name: qualitool_db
    ports:
      - 5432:5432
    env_file:
      - qualitool.env
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./dbinit:/docker-entrypoint-initdb.d
  sso:
    image: "quay.io/keycloak/keycloak"
    container_name: sso
    ports:
      - 8083:8443
    env_file:
      - qualitool.env
    depends_on:
      - database
    volumes:
      - ./cert:/etc/x509/https

    
  backend:
    image: "gcr.io/qualitool/qualitool_be"
    container_name: qualitool_be
    ports:
      - 8082:8082
    env_file:
      - qualitool.env
    volumes:
      - ./cert:/cert
      - ./static:/static
      - ./init:/init
    depends_on:
      - database
      
  frontend:
    image: "gcr.io/qualitool/qualitool_fe"
    container_name: qualitool_fe
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:/etc/nginx/certs
        
volumes:
  database-data: